/// <reference types="react-native-css/types" />

// NOTE: This file should not be edited and should be committed with your source code. It is generated by react-native-css. If you need to move or disable this file, please see the documentation.

/// <reference types="nativewind/types" />

// This helps VS Code recognize your custom theme extensions
declare module "nativewind" {
  export interface Theme {
    fontFamily: {
      rubik: string;
      "rubik-bold": string;
      "rubik-medium": string;
      "rubik-light": string;
      "rubik-extrabold": string;
      "rubik-semibold": string;
    };
  }
}
